### PR TITLE
Touched something

### PR DESCRIPTION
**Pull request by Umoren**
I moved the Submit and Reset buttons a little and made them more responsive.

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
@Umoren you just sent a bug!
Buttons are not responsive, spacing's are irregular.
This is a sample of your PR.
image

Kindly check and fix you errors, until then, I can't merge this PR.

**Comment by BolajiAyodeji** [comment]
@Umoren , submit button does not work anymore and hover is disabled.
It is not fully responsive on all screens.
image
I can't merge this PR yet.

**Comment by BolajiAyodeji** [comment]
@Umoren I would close this PR in 24hours if nothing is fixed!
Kindly fix the errors in this PR.
Thank you!

**Comment by Umoren** [comment]
Please close it.
Thank you.

**Comment by BolajiAyodeji** [comment]
@Umoren Alright!

**Pull request closed without merging**
