### PR TITLE
Add Python Version

### PR DESCRIPTION
**Pull request by CITGuru**
Hey bolaji, 

I interpreted your project to python, so python users can use it. It can be installed from PyPI using pip.
https://github.com/CITGuru/netty-finder-python/

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
This is Awesome!
Thank you @CITGuru

**Comment by CITGuru** [comment]
@BolajiAyodeji A nodejs version is coming, interpreted it already, will push it to npm and add it to this

**Comment by BolajiAyodeji** [comment]
This is great!
Thank you @CITGuru :+1:

**Comment by BolajiAyodeji** [comment]
So the current python version can only be used by Developers right?

**Comment by CITGuru** [comment]
@BolajiAyodeji Yes for python devs

**Comment by BolajiAyodeji** [comment]
Alright!
Cool @CITGuru

**Comment by BolajiAyodeji** [comment]
Thanks for contributing

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @CITGuru  for code

**Pull request merged**
