### PR TITLE
Fixed #18 clearing input field after submit and added Submit on Enter support!

### LINKED ISSUE #18: Clear Button
_Hello Guys_
This project is really cool. 
I think we could remove the clear button and use the submit button for clearing the form inputs after submission.
There's a similar solution  [here](https://stackoverflow.com/questions/14589193/clearing-my-form-inputs-after-submission#_=_)
This is the first time i'm contributing to a project so bear with my novice inefficiencies.

### PR DESCRIPTION
**Pull request by devHammed**
1. Fixed #18 clearing input field after submit
2. Added support for Submit on `Enter` key press instead of relying on button click

### CODE REVIEW

**Comment by BolajiAyodeji** [comment]
I see a lot of spacings in your PR
Can you format your code and send another commit?
Thank you @devHammed

**Comment by BolajiAyodeji** [comment]
Ooops that style is not allowed in this project!
Lets test the PR, I would do the formatting.
Thank you!

**Comment by BolajiAyodeji** [comment]
@devHammed PR works fine although you changed the submit button styles?

**Comment by BolajiAyodeji** [comment]
Revert the previous styles for the submit button in a new commit? @devHammed

**Comment by devHammed** [comment]
No, I simply removed the onClick and changed the type attribute to submit, but I think your CSS relies on `input[type=button]`.

**Comment by devHammed** [comment]
I have fixed the CSS.

**Comment by BolajiAyodeji** [comment]
@all-contributors please add @devhammed  for code

**Pull request merged**
